name: Deploy Lambda

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and Publish Dependencies Layer
        run: |
          # Create a folder for the layer with the correct structure.
          mkdir -p layer/python

          # Use Docker with the AWS SAM build image for Python 3.11 to install dependencies.
          docker run --rm -v "$(pwd)/layer/python":/var/task/python public.ecr.aws/sam/build-python3.11 \
            pip install --no-cache-dir --only-binary=:all: pandas numpy -t /var/task/python

          # Debug: list contents to verify installation.
          echo "Contents of layer/python after installation:"
          ls -la layer/python

          # Zip the folder so that the ZIP file has a top-level "python" directory.
          cd layer && zip -r ../dependencies.zip python && cd ..
          echo "Listing contents of dependencies.zip:"
          unzip -l dependencies.zip

          # Upload the dependencies ZIP to S3.
          aws s3 cp dependencies.zip s3://${{ secrets.AWS_S3_BUCKET }}/dependencies.zip

          # Publish the layer using the S3-hosted ZIP file.
          LAYER_VERSION=$(aws lambda publish-layer-version \
            --layer-name PandasNumpyLayer \
            --content "S3Bucket=${{ secrets.AWS_S3_BUCKET }},S3Key=dependencies.zip" \
            --compatible-runtimes python3.11 \
            --query 'Version' --output text)
          echo "LAYER_VERSION=$LAYER_VERSION" >> $GITHUB_ENV
          echo "Published layer version: $LAYER_VERSION"

      - name: Package Lambda Function
        run: |
          mkdir function
          cp lambda/lambda_function.py function/
          cd function && zip -r ../function.zip . && cd ..

      - name: Upload Lambda Package to S3
        run: |
          aws s3 cp function.zip s3://${{ secrets.AWS_S3_BUCKET }}/function.zip

      - name: Check if Lambda Exists
        id: check_lambda
        continue-on-error: true
        run: aws lambda get-function --function-name EkimetricsDataProcessing

      - name: Create Lambda Function
        if: steps.check_lambda.outcome == 'failure'
        run: |
          aws lambda create-function --function-name EkimetricsDataProcessing \
            --runtime python3.11 \
            --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_LAMBDA_ROLE }} \
            --handler lambda_function.lambda_handler \
            --code "S3Bucket=${{ secrets.AWS_S3_BUCKET }},S3Key=function.zip" \
            --environment "Variables={S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET }}}" \
            --layers arn:aws:lambda:us-east-1:${{ secrets.AWS_ACCOUNT_ID }}:layer:PandasNumpyLayer:${{ env.LAYER_VERSION }} \
            --timeout 300 \
            --ephemeral-storage Size=512 \
            --memory-size 1024 \
            --region us-east-1

      - name: Wait for Lambda Function to Become Active
        run: |
          RETRY=10
          while [ $RETRY -gt 0 ]; do
            STATE=$(aws lambda get-function-configuration --function-name EkimetricsDataProcessing --query 'State' --output text --region us-east-1)
            if [ "$STATE" = "Active" ]; then
              echo "Lambda function is Active."
              break
            fi
            echo "Lambda function state: $STATE. Waiting 10 seconds..."
            sleep 10
            RETRY=$((RETRY-1))
          done
          if [ "$STATE" != "Active" ]; then
            echo "Lambda function did not become Active in time."
            exit 1
          fi

      - name: Deploy Lambda Function Code
        run: |
          aws lambda update-function-code --function-name EkimetricsDataProcessing --zip-file fileb://function.zip --region us-east-1

      - name: Add S3 Trigger to Lambda
        run: |
          echo "Waiting for previous updates to complete..."
          sleep 30  # Adjust if needed
          set -e
          if ! aws lambda get-policy --function-name EkimetricsDataProcessing | grep -q s3-trigger; then
            aws lambda add-permission \
              --function-name EkimetricsDataProcessing \
              --statement-id s3-trigger \
              --action "lambda:InvokeFunction" \
              --principal s3.amazonaws.com \
              --source-arn arn:aws:s3:::${{ secrets.AWS_S3_BUCKET }} \
              --source-account ${{ secrets.AWS_ACCOUNT_ID }} \
              --region us-east-1
          fi
          aws s3api put-bucket-notification-configuration \
            --bucket ${{ secrets.AWS_S3_BUCKET }} \
            --notification-configuration '{
              "LambdaFunctionConfigurations": [{
                "LambdaFunctionArn": "arn:aws:lambda:us-east-1:${{ secrets.AWS_ACCOUNT_ID }}:function:EkimetricsDataProcessing",
                "Events": ["s3:ObjectCreated:*"]
              }]
            }'
