name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Dependencies
        run: |
          pip install boto3 pandas numpy -t package/
          cp lambda_function.py package/
          cd package && zip -r ../function.zip .

      - name: Package Lambda
        run: |
          zip -r function.zip lambda_function.py boto3 pandas numpy

      - name: Create Lambda Function (if it doesn't exist)
        run: |
          aws lambda get-function --function-name EkimetricsDataProcessing || \
          aws lambda create-function --function-name EkimetricsDataProcessing \
          --runtime python3.11 --role arn:aws:iam::<YOUR_ACCOUNT_ID>:role/<YOUR_LAMBDA_ROLE> \
          --handler lambda_function.lambda_handler --zip-file fileb://function.zip \
          --region us-east-1

      - name: Deploy Lambda Function Code
        run: |
          aws lambda update-function-code --function-name EkimetricsDataProcessing --zip-file fileb://function.zip --region us-east-1

      - name: Ensure Lambda Runtime is Python 3.11
        run: |
          aws lambda update-function-configuration --function-name EkimetricsDataProcessing --runtime python3.11 --region us-east-1
